services:
  - type: web
    name: my-choral-part
    env: node
    buildCommand: npm install && node generate-version.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: choral-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
